
#ifndef _AMXMODX_AUTO_VERSION_INFORMATION_H_
#define _AMXMODX_AUTO_VERSION_INFORMATION_H_

#define SVN_VERSION_STRING  "1.8.1"
#define SVN_VERSION_DWORD   1, 8, 1, 0
#define SVN_VERSION_PRODUCT "1.8.1"
#define SVN_VERSION         SVN_VERSION_STRING
#define SVN_BUILD_ID        "3983:1dba9eaeb905dce526b39dc7f8f2a5d435f3fb72"

#endif // _AMXMODX_AUTO_VERSION_INFORMATION_H_
