/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <hamsandwich>
#include <csgo>

new g_iWymaganaIloscGraczy;

new g_pCvarSzansaNaDropKlucza, g_pCvarSzansaNaDropSkrzynki, g_pCvarFlagaVip;

public plugin_init() {
	register_plugin("CSGO Mod: Super VIP dodatki", "1.0", "donaciak.pl");
	
	g_pCvarSzansaNaDropKlucza = register_cvar("csgo_szansanadropkluczasvip", "100");
	g_pCvarSzansaNaDropSkrzynki = register_cvar("csgo_szansanadropskrzynkisvip", "100");
	g_pCvarFlagaVip = register_cvar("csgo_flagasvip", "sz");
	register_cvar("csgo_szansalosowanieskrzynkisvip", "5");
	register_cvar("csgo_cenakluczasvip", "100");
	
	RegisterHam(Ham_Killed, "player", "fw_Smierc_Post", 1);
	
	g_iWymaganaIloscGraczy = get_cvar_num("csgo_wymaganailoscgraczygranie");
}

public fw_Smierc_Post(id, iAtt, iShGb) {
	if(get_playersnum() < g_iWymaganaIloscGraczy || !is_user_connected(iAtt) || get_user_team(id) == get_user_team(iAtt) || !is_user_vip(iAtt)) {
		return;
	}
	
	if(random_num(1, get_pcvar_num(g_pCvarSzansaNaDropKlucza)) == 1) {
		csgo_set_user_keys(iAtt, csgo_get_user_keys(iAtt) + 1);
		csgo_print_message(iAtt, "WOW! Udalo Ci sie znalezc^x03 klucz do skrzynek!");
	}
	
	if(random_num(1, get_pcvar_num(g_pCvarSzansaNaDropSkrzynki)) == 1) {
		new iSkrzynka = random_num(1, csgo_get_cratesnum());
		new szSkrzynka[32]; csgo_get_crate_name(iSkrzynka, szSkrzynka, 31);
		
		csgo_set_user_crates(iAtt, iSkrzynka, csgo_get_user_crates(iAtt, iSkrzynka) + 1);
		csgo_print_message(iAtt, "WOW! Udalo Ci sie znalezc^x03 %s!", szSkrzynka);
	}
}

stock is_user_vip(id) {
	static iFlagi;
	
	if(!iFlagi) {
		new szFlagi[32];
		get_pcvar_string(g_pCvarFlagaVip, szFlagi, 31);
		iFlagi = read_flags(szFlagi);
	}
	
	if(get_user_flags(id) & iFlagi) {
		return 1;
	}
	
	return 0;
}
