
#if defined _amxmodx_version_included
  #endinput
#endif
#define _amxmodx_version_included

#define AMXX_VERSION_TAG        "Re"
#define AMXX_VERSION_CSET       ""
#define AMXX_VERSION_MAJOR      "1"
#define AMXX_VERSION_MINOR      "8"
#define AMXX_VERSION_RELEASE    "3"
#define AMXX_VERSION_LOCAL_REV  "7"
#define AMXX_VERSION            1.83
#define AMXX_VERSION_NUM        183

stock const AMXX_VERSION_STR[] = "1.8.3-Re";
