/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <smsshop>

native set_player_key(id, ile);
native get_player_key(id);

new g_iUsluga;

#define NAZWA_DL "Klucze do skrzynki" 				//Nazwa uslugi wyswietlana w menu
#define NAZWA_KR "klucze" 				//nazwa uslugi uzywana w logach, jako okienko MOTD itd.

new const g_szJednostkaIlosci[][][] = {
	{ "10", "10 kluczy" },
	{ "20", "20 kluczy" },
	{ "40", "40 kluczy" },
	{ "50", "50 kluczy" }
	//Wypisz tutaj po kolei jednostke ilosci uslug
	//Format: "kr. jednostka", "dl. jednostka"
	//dluga jednostka - wyswietlana jest w np. menu
	//krotka jednostka - wykorzystywana w skryptach
	//Pamietaj ze ostatnia linijka nie ma na koncu po klamrze przecinka!
}

new const g_szCena[][][] = {
	{ "1,23", "1,23 zl SMS / 1 zl przelew / 1 zl PSC" },
	{ "3,69", "3,69 zl SMS / 2 zl przelew / 2 zl PSC" },
	{ "7,38", "7,38 zl SMS / 6 zl przelew / 6 zl PSC" },
	{ "11,07", "11,07 zl SMS / 9 zl przelew / 9 zl PSC" }
	//Wypisz tutaj w takiej samej kolejnosci jak dlugosci uslug ich ceny
	//Format: "kr. cena", "dl. cena"
	//krotka cena - cena SMSa uslugi - zlotowki i grosze oddzielone przecinkiem
	//dluga cena - cena wyswietlana w menu
	//Pamietaj ze ostatnia linijka nie ma na koncu po klamrze przecinka!
}

public plugin_init() 
{
	new szNazwa[64]; formatex(szNazwa, 63, "Sklep SMS: Usluga %s", NAZWA_DL);
	register_plugin(szNazwa, "1.0", "d0naciak");
	
	g_iUsluga = ss_register_service(NAZWA_DL, NAZWA_KR);
	
	for(new i = 0; i < sizeof g_szJednostkaIlosci; i++)
		ss_add_service_qu(g_iUsluga, g_szJednostkaIlosci[i][1], g_szJednostkaIlosci[i][0], g_szCena[i][1], g_szCena[i][0]);
}

public ss_buy_service_post(id, iUsluga, iJednostkaIlosci)
{
	if(iUsluga != g_iUsluga)
		return SS_CONTINUE;
	
	set_player_key(id, get_player_key(id) + str_to_num(g_szJednostkaIlosci[iJednostkaIlosci][0]));
	
	ss_finalize_user_service(id);
	
	return SS_CONTINUE;
}
