/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <nvadmins>
#include <smsshop>

new g_iUsluga;

#define NAZWA_DL "VIP" 			//Nazwa uslugi wyswietlana w menu
#define NAZWA_KR "vip" 			//nazwa uslugi uzywana w logach, jako okienko MOTD itd.
#define FLAGA "t"				//flaga jaka ma dostac gracz

new const g_szJednostkaIlosci[][][] = {
	{ "3", "3 dni" },
	{ "30", "30 dni" }
	//Wypisz tutaj po kolei dlugosci uslug
	//Format: "kr. czas", "dl. czas"
	//dlugi czas - wyswietlany jest w np. menu
	//krotki czas - wykorzystywany w skryptach, aby dana usluga byla dostepna na zawsze wpisz -1
	//Pamietaj ze ostatnia usluga nie ma na koncu po klamrze przecinka!
}

new const g_szCena[][][] = {
	{ "1,23", "1,23 zl SMS" },
	{ "11,07", "11,07 zl SMS / 9 zl przelew / 10 zl PSC" }
	//Wypisz tutaj w takiej samej kolejnosci jak dlugosci uslug ich ceny
	//Format: "kr. cena", "dl. cena"
	//krotka cena - cena SMSa uslugi - zlotowki i grosze oddzielone przecinkiem
	//dluga cena - cena wyswietlana w menu
	//Pamietaj ze ostatnia linijka nie ma na koncu po klamrze przecinka!
}


public plugin_init() 
{
	new szNazwa[64]; formatex(szNazwa, 63, "Sklep SMS: Usluga %s", NAZWA_DL);
	register_plugin(szNazwa, "1.0", "d0naciak");
	
	g_iUsluga = ss_register_service(NAZWA_DL, NAZWA_KR, 0);
	
	for(new i = 0; i < sizeof g_szJednostkaIlosci; i++)
		ss_add_service_qu(g_iUsluga, g_szJednostkaIlosci[i][1], g_szJednostkaIlosci[i][0], g_szCena[i][1], g_szCena[i][0]);
	
	
}

public ss_buy_service_post(id, iUsluga, iJednostkaIlosci)
{
	if(iUsluga != g_iUsluga)
		return SS_CONTINUE;
	
	new szDataWaznosci[32], szNick[64];
			
	get_user_name(id, szNick, 63);
	
	if(equal(g_szJednostkaIlosci[iJednostkaIlosci][0], "-1")) 
		copy(szDataWaznosci, 31, g_szJednostkaIlosci[iJednostkaIlosci][0]);
	else
		na_get_data_after_days(str_to_num(g_szJednostkaIlosci[iJednostkaIlosci][0]), szDataWaznosci, 31);
	
	na_add_admin(szNick, 1, "", FLAGA, szDataWaznosci, NAZWA_KR);
	
	ss_finalize_user_service(id);
	
	return SS_CONTINUE;
}
